### ISSUE TITLE
Docs for docker install are completely wrong

### ISSUE THREAD

**Issue by mabushey** [utkarshcmu/wizzy#112]
https://utkarshcmu.github.io/wizzy-site/home/getting-started/:
```
Using docker. Pull the latest docker image wizzy-docker
$ docker pull utkarshcmu/wizzy
```

That's not an install, this makes the image available locally to install. This step is completely optional as a docker run will automatically do a pull.

The docs should say something like "Example of running wizzy version: `docker run --rm -it utkarshcmu/wizzy wizzy version`.

**Comment by utkarshcmu** [comment]
Thanks @mabushey for suggesting this as I am completely new to docker so was not aware about these things!

**Comment by utkarshcmu** [comment]
Fixed in docs

**Comment by grobgl** [comment]
Just came across this: the updated docker command doesn't seem to work for me either. For anyone interested in using dockerised wizzy to import dashboards, here's what I do:

```bash
 docker run \
     --name wizzy \
     --rm \
     --entrypoint /bin/ash \
     -v /full/path/to/dashboards/backup:/app/dashboards \
     utkarshcmu/wizzy \
     -c "wizzy init && \
         wizzy set grafana url http://grafana:3000 && \
         wizzy set grafana username admin && \
         wizzy set grafana password admin && \
         wizzy import dashboards"
```
