### ISSUE TITLE
TypeError: Cannot read property 'statusCode' of undefined

### ISSUE THREAD

**Issue by balopat** [utkarshcmu/wizzy#17]
I get the issue below when trying to connect to grafana simply do a `wizzy show orgs`. 
Grafana is behind https with ldap. I'm running wizzy using npm 3.10.8, node 5.4.1 on windows...

````
$ wizzy show orgs
C:\Users\<user>\AppData\Roaming\npm\node_modules\wizzy\src\grafana.js:409
                output += 'Grafana API response status code = ' + response.statusCode;
                                                                          ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.printResponse [as _callback] (C:\Users\<user>\AppData\Roaming\npm\node_modules\wizzy\src\grafana.js:409:63)
    at self.callback (C:\Users\<user>\AppData\Roaming\npm\node_modules\wizzy\node_modules\request\request.js:186:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (C:\Users\<user>\AppData\Roaming\npm\node_modules\wizzy\node_modules\request\request.js:845:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:262:9)
    at emitOne (events.js:77:13)
    at TLSSocket.emit (events.js:169:7)
````

**Comment by utkarshcmu** [comment]
which version of wizzy are you using? 0.4.0?

**Comment by utkarshcmu** [comment]
Also, what is your role in Grafana? an editor or an admin or a viewer?

**Comment by utkarshcmu** [comment]
Also, if you are on Grafana Slack, I am always available to fix issues regarding wizzy - https://raintank.slack.com/messages/wizzy/details/

**Comment by utkarshcmu** [comment]
We need LDAP support for wizzy ... thats the requirement... :|

**Comment by utkarshcmu** [comment]
Need to resolve this https://github.com/grafana/grafana/issues/6911 for resolving this error!

**Comment by utkarshcmu** [comment]
Waiting for https://github.com/grafana/grafana/pull/6940 to get merged!

**Comment by utkarshcmu** [comment]
This error should be fixed with Grafana 4.1.

**Comment by jamessewell** [comment]
This seems to still be broken for me:

**wizzy: 0.5.8
node: 6.9.4
grafana: 4.1.2**
```

{
  "config": {
    "grafana": {
      "username": "admin",
      "password": "admin",
      "url": "https://192.168.2.251:3000"
    }
  }
}
```


```
#wizzy list dashboards
/root/wizzy/wizzy/src/remote/grafana.js:277
                                output += 'Grafana API response status code = ' + response.statusCode;
                                                                                          ^

TypeError: Cannot read property 'statusCode' of undefined
    at Request.saveHandler [as _callback] (/root/wizzy/wizzy/src/remote/grafana.js:277:65)
    at self.callback (/root/wizzy/wizzy/node_modules/request/request.js:187:22)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestError (/root/wizzy/wizzy/node_modules/request/request.js:859:8)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:310:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
```

**Comment by jamessewell** [comment]
Oh, it's my unsigned cert

I can fix by adding 

`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

At the start of importSrv.js, or by adding

`      rejectUnauthorized: false
`
To each request options.

**Comment by rgeniesse** [comment]
@jamessewell, thanks for posting how to fix this. I am seeing this too even on http, but adding that lline to importSrv.js resolved it for me for some reason.

centos: 7.2.1511
grafana: 4.2.0
wizzy: 0.5.9
npm: 3.10.10
node: 6.10.1

**Comment by jamessewell** [comment]
The other option is to use a signed certificate!

**Comment by vinlok** [comment]
@utkarshcmu @jamessewell 
I am facing the same issue with unsigned certificate. I am using 0.6.0 version of wizzy, and I added process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
to importSrv.js, however, it still errors with same exception.

**Comment by ArgonQQ** [comment]
> @utkarshcmu @jamessewell
> I am facing the same issue with unsigned certificate. I am using 0.6.0 version of wizzy, and I added process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
> to importSrv.js, however, it still errors with same exception.
> 
> Any idea what I am doing wrong here.
> 
> Update:
> I also tried adding {rejectUnauthorized:false}, to each request call in importSrv.js, however, I am still getting the same error.
> 
> Any suggestions on how to proceed further will be really helpful.

Getting the same errors as well - any updates here? Is there no option to simply skip SSL verification? Would be highly appreciated!

**Comment by jamessewell** [comment]
I actually came back to this and managed to eventually get it going again
with something similar to this.

Wizzy doesn’t work with recent Grafana though, unless it gets an update
it’s not very useful anymore.

**Comment by tuan-phan** [comment]
Any update in this issue?
Currently, I am facing it and don't have any solution :(

**Comment by jamessewell** [comment]
I'd say unless something big happens Wizzy is dead at this point.

You won't get support for new version of Grafana - and with the recent jumps you'd be silly not to use those versions.

**Comment by Tikam02** [comment]
it is dead now,not supporting new versions
