### ISSUE TITLE
Add S3 integration

### ISSUE THREAD

**Issue by utkarshcmu** [utkarshcmu/wizzy#20]
Upload stuff to s3

Fownload stuff from s3

**Comment by sstarcher** [comment]
How are you thinking about implementing this.  Would this be a setting to work against a remote location `$ wizzy set remote s3 BUCKET` or a cli command such as `wizzy backup LOCATION` `wizzy restore LOCATION`

**Comment by utkarshcmu** [comment]
Hi @sstarcher,

At least to set s3 config, i was thinking to have:

Wizzy set s3 access_key
Wizzy set s3 secret_key
Wizzy set s3 bucket_name

Then next we can add s3 commands to take a backup/restore/upload/dowload things from s3.

Any suggestions?

**Comment by sstarcher** [comment]
Sounds reasonable, but you may want to include bucket_path

**Comment by utkarshcmu** [comment]
Yeah good catch, you are correct. That should also be the part of s3 configuration 👍

**Comment by Udayrakesh** [comment]
ill work on this in freetime

**Comment by Udayrakesh** [comment]
#48

**Comment by utkarshcmu** [comment]
Nice work! 👍
