### ISSUE TITLE
Feature Request: Delete row/panel in a dashboard

### ISSUE THREAD

**Issue by daniellee** [utkarshcmu/wizzy#28]
I'd like to submit a feature request for deleting a row or panel. 

`wizzy delete row 3`
`wizzy delete panel 1.1`

### Context:

Love the tool - it is great for updating dashboards in a Grafana app. The order of the attributes changes every time a dashboard is exported from Grafana which makes it hard to see what has changed in git diffs. Copying rows and panels with Wizzy minimizes that. After copying a row/panel from a dashboard into my app dashboard I often want to remove/replace a row or panel.

**Comment by utkarshcmu** [comment]
Implemented and merged into master

**Comment by utkarshcmu** [comment]
The commands will be :
```
wizzy remove row 2
wizzy remove panel 3.2
```

**Comment by utkarshcmu** [comment]
The reason to have "remove" was to make sure that "remove" is used for local change and "delete" is used for remote change.

**Comment by daniellee** [comment]
That was fast! Thank you very much.
