### ISSUE TITLE
Datasource Export not working when datasource does not exist

### ISSUE THREAD

**Issue by sstarcher** [utkarshcmu/wizzy#36]
Grafana 4.0.0
Wizzy 0.5

```
 wizzy export datasource 2
Output:
"<*api.NormalResponse Value>"
✔ Datasource 2 export successful.
```

Nothing shows up in grafana.

**Comment by sstarcher** [comment]
Looks like the issue is if the specific index of the datasource does not exist the code fails.  As it's expecting the index to already exist.

**Comment by utkarshcmu** [comment]
@sstarcher So, just to understand the issue better, you are trying to create a new datasource in Grafana via export command?

**Comment by sstarcher** [comment]
I imported all of the datasources, dashboards etc.  I created a new instance of Grafana and wanted to import all of the resources from the old Grafana into the new Grafana.

**Comment by utkarshcmu** [comment]
Got it... will fix the issue in next version... which will be released tonight... Thanks for reporting.. 👍

**Comment by sstarcher** [comment]
#37 fixes part of the issue

**Comment by utkarshcmu** [comment]
Moved datasource interaction using "name" instead of "ids"
