### ISSUE TITLE
Export of multiple datasources returns with exit code 0 when some fail

### ISSUE THREAD

**Issue by sstarcher** [utkarshcmu/wizzy#40]
```
wizzy export datasources
Output:
{
  "id": 1,
  "message": "Datasource added"
}
✔ Datasource export successful.
Output:
Grafana API response status code = 500
No error body from Grafana API.
✘ Datasource export failed.
Output:
Grafana API response status code = 500
No error body from Grafana API.
✘ Datasource export failed.
Output:
{
  "id": 2,
  "message": "Datasource added"
}
✔ Datasource export successful.
```

**Comment by utkarshcmu** [comment]
Are you using sqlite?

**Comment by sstarcher** [comment]
Yes

**Comment by utkarshcmu** [comment]
So, the rootcause of the error is database locked down in sqlite. You might want to follow this thread - https://github.com/grafana/grafana/issues/7013

What we can do until grafana fixes the bug to use 'sync-requests' instead of 'requests'. Will make the change sometime today.

**Comment by utkarshcmu** [comment]
@sstarcher Made the export code to use sync-request. Please try it now!

**Comment by utkarshcmu** [comment]
This should be fixed too. Please reopen if not fixed!
