### ISSUE TITLE
[FEATURE REQUEST] tag management

### ISSUE THREAD

**Issue by xinity** [utkarshcmu/wizzy#51]
It could be cool to be able to manage dashboard tags through wizzy as well.

seems to be achievable regarding API documentations:
http://docs.grafana.org/http_api/dashboard/#tags-for-dashboard

thanks a lot for this awesome tool !

**Comment by utkarshcmu** [comment]
So, would you like wizzy to list tags?

something like `wizzy list dashboard-tags` ?

**Comment by utkarshcmu** [comment]
we want the ability to copy/extract/insert dashboard-tags from one dashboard to another.

See the possibility to add a new tag or remove tag from dashboards too!

**Comment by utkarshcmu** [comment]
`wizzy list dashboard-tags` command added!

**Comment by utkarshcmu** [comment]
```
wizzy copy dash-tags
wizzy extract dash-tags
wizzy insert dash-tags
```

The above commands are now in master!
