### ISSUE TITLE
Add connecting to multiple grafana installations

### ISSUE THREAD

**Issue by utkarshcmu** [utkarshcmu/wizzy#57]
Support wizzy grafana context.... 'prod' 'dev' etc...

**Comment by utkarshcmu** [comment]
may be `switch` command

**Comment by utkarshcmu** [comment]
```
wizzy add grafana prod
wizzy set context grafana prod
wizzy set grafana url http://localhost:3000
wizzy add grafana dev
wizzy set context grafana dev
wizzy set grafana url http://localhost:3000
```

**Comment by utkarshcmu** [comment]
Commands added in master!

**Comment by AlKapkone** [comment]
Hello, Utkarsh. So, is it possible to add few grafana instances (url, user, pass) in one config file simultaneously? I have multiple grafana`s and i want to share dashboards beetween them (multiply dashboards between multiply grafana`s)?
