### ISSUE TITLE
List/Change panels using a particular datasource

### ISSUE THREAD

**Issue by utkarshcmu** [utkarshcmu/wizzy#58]
- [x] List panels using a datasource
- [x] Change from old datasource to new on a dashboard...

**Comment by utkarshcmu** [comment]
@digrich... I think this will be useful for your use case... and will help many others too

**Comment by digrich** [comment]
Thanks @utkarshcmu for taking it as a feature request.

**Comment by utkarshcmu** [comment]
`wizzy list panels datasource my-graphite` this command will list datasources on a dashboard with a datasource name

**Comment by utkarshcmu** [comment]
One can write scripts to change dashboard names to something else now using wizzy!

**Comment by r4j4h** [comment]
Does this work with `null` dashboards or mixed settings?
