### ISSUE TITLE
Switch org command to switch Grafana context!

### ISSUE THREAD

**Issue by kaushiksriram100** [utkarshcmu/wizzy#69]
my grafana has a default org configured (doesn't require login). when I run wizzy list dashboards, it shows only the dashboards in that default org. How can I view dashboards from different org that my login has permissions. I have set the username/passd.

**Comment by utkarshcmu** [comment]
Currently, the way to do it to go to your Grafana UI and switch the org and then try 'list dashboards'.
But I agree that there is a need to switch the org. I'll try to create a command:
`wizzy switch org ORG-ID` to switch to a different org in the next version (which will be out in next 2  days).

**Comment by utkarshcmu** [comment]
Depends on https://github.com/grafana/grafana/issues/7288

**Comment by utkarshcmu** [comment]
`wizzy switch grafana org ORG_ID` is the command to switch to the another org via CLI.

Merged into master!
