### ISSUE TITLE
Question: What do you prefer spaces or tabs?

### ISSUE THREAD

**Issue by rbo** [utkarshcmu/wizzy#73]
Hi,

i would like to add support to set custom http headers and improve the error handling. Sandly i don't know what you prefer spaces or tabs, because i found both.

<img width="821" alt="screen shot 2017-01-19 at 10 20 21" src="https://cloud.githubusercontent.com/assets/36604/22100901/6342b020-de31-11e6-8c5a-fc1317031037.png">

Thanks
Robert

**Comment by utkarshcmu** [comment]
Tabs are preferable. Will fix the code using jshint very soon!

**Comment by utkarshcmu** [comment]
Fixed with jshintrc : indent = 2
