### ISSUE TITLE
Changing copied row also changes original row

### ISSUE THREAD

**Issue by slnowak** [utkarshcmu/wizzy#86]
Hi, 

I wanted to play around with wizzy today, but I had some issues while copying rows.
Here's what I did:
1) wizzy import dashboards
2) wizzy set context dashboard my-dashboard
3) wizzy copy row 1 2
4) wizzy export my-dashboard

Now I wanted to edit newly inserted row (to change queries a little bit) directly from grafana, but it seems that any change to a copy also affects the origin row.

Same issue holds for row extract/insert.

// edit
After a quick investigation it seems like wizzy blindly copies panels, without changing panel IDs.

**Comment by utkarshcmu** [comment]
Will look into it asap!

**Comment by utkarshcmu** [comment]
This bug is fixed in master now. Thanks for reporting!

**Comment by utkarshcmu** [comment]
@slnowak - wizzy 0.5.7 is released. This bug is fixed in this version. Feel free to reopen the bug if the problem still persists.
