### ISSUE TITLE
Ability to import dashboards without deleting old versions?

### ISSUE THREAD

**Issue by PaulCapestany** [utkarshcmu/wizzy#89]
Sorry if this is obvious and I missed it in the docs somewhere, but lets say we've imported all our existing dashboards via `wizzy import dashboards`, and then someone updates a few dashboards via Grafana's gui, is there a proper way to grab those specific updates via wizzy? 

It looks like re-running `wizzy import dashboards` again results in the existing dashboard json files being completely over-written, which kind of seems like it'd defeat the purpose of having them in git history :)

**Comment by tinder-ubhatnagar** [comment]
How about this if we want to track the changes?
```
wizzy import dashboards
git init
git add dashboards
git commit -m "Added dashboards to git repo"
```
Now lets say the someone made some changes in the GUI and you pull the changes again.
```
wizzy import dashboards
```
You are correct that this will overwrite the existing dashboards in the dashboards directory. But then you can run:
```
git diff
```
to find what changed in the dashboards.

Does this resolves your question?

**Comment by PaulCapestany** [comment]
Well, unless I'm mistaken or missing something, if I follow those steps the files are still ~~completely over-written~~ (I'd previously misspoken) deleted and replaced with the newly imported files, and so doing `git diff` does not result in actually being able to see any diffs via `git diff` for me.

**Comment by utkarshcmu** [comment]
`git diff` might not be helpful for you I guess. Also, you are right that whenever you import dashboards, the dashboards are overwritten. Anyways, we can do the following to know what changed in the dashboards.

Import all dashboards:
```
wizzy import dashboards
git init
git add dashboards
git commit -m "First commit of dashboards"
```

Create a temp branch for the new changes:
```
git checkout -b 'test_branch'
```

Now import all the dashboards again and do a diff between branches:
```
wizzy import dashboards
git status
git diff master...test_branch
```

Also, you can create a PR from the test_branch against the master branch and see the differences too.

Hopefully now you should be able to see the changes made on GUI with what you have in your Git master branch.

Let me know if this still does not solve the issue. I would be happy to answer as I might be missing something too. :)

**Comment by sstarcher** [comment]
It might be helpful if possible to drop certain fields like the dashboard id

**Comment by utkarshcmu** [comment]
@PaulCapestany I think now I got your point. We should have this functionality to import old dashboards too. It is a valid feature request.

**Comment by sstarcher** [comment]
@PaulCapestany is the main change you are seeing is every dashboard has it's `id` updated?

This should fix that issue - https://github.com/utkarshcmu/wizzy/commit/c91e17f988603f65338cbd8ae354c41d946b957c

**Comment by sstarcher** [comment]
Let me know if that did not accomplish what you wanted.

**Comment by PaulCapestany** [comment]
@sstarcher appreciate the heads-up. Grabbed your commit (as well as other recent commits) and ran `npm install && npm link`, and then the following: 

```
grafana-entities ▸ wizzy import dashboards
Importing 350 dashboards:
```

Unfortunately, after wizzy is done running for some reason it seems that now no files are updated or imported at all (and when I delete previously downloaded dashboards, no new files appear in this case either).

**Comment by sstarcher** [comment]
@PaulCapestany try installing the latest release 0.5.9.
I'm currently running it without any issues.

**Comment by PaulCapestany** [comment]
@sstarcher unless I'm missing something, there isn't a 0.5.9 release, and the latest release is [0.5.8](https://github.com/utkarshcmu/wizzy/tree/0.5.8). I tried running that, as well as the most recent commit @ e3795f25bd79756f148ac6e81946ffc751d0d9ea, and had the same issue of wizzy seemingly not downloading anything at all 😕

**Comment by tinder-ubhatnagar** [comment]
@PaulCapestany You are correct, there is no 0.5.9 release yet. Try running 0.5.7 version. That should get your dashboards. I am also seeing some issues with 0.5.8 currently. Will fix it asap.
