### ISSUE TITLE
Add auth proxy support via cookie settings

### ISSUE THREAD

**Issue by utkarshcmu** [utkarshcmu/wizzy#90]
To connect to grafana behind an auth proxy, set cookie via "grafana cookie"

**Comment by utkarshcmu** [comment]
As as temporary solution, please use:
wizzy set grafana headers Cookie "CookieName=CookieValue"

**Comment by isopropylcyanide** [comment]
> As as temporary solution, please use:
> `wizzy set grafana headers Cookie "CookieName=CookieValue"`

This. Thanks for putting the workaround out.
