### ISSUE TITLE
Exporting dashboard 404's

### ISSUE THREAD

**Issue by sstarcher** [utkarshcmu/wizzy#91]
With newer versions of wizzy when exporting alot of dashboards I seem to be getting alot more 404's.  I'm guessing this is still related to sqlite locking?

```
Grafana API response status code = 404
No error body from Grafana API.```

**Comment by utkarshcmu** [comment]
It is related to sqlite locking. I am making export sequential instead of parallel so that we atleast guarantee reliability.

**Comment by utkarshcmu** [comment]
I have made exports serial. Fixed in master. Feel free to open the issue if it still exists.

**Comment by utkarshcmu** [comment]
Wizzy 0.5.7 released. Plz check for these 404s in the new version.

**Comment by sstarcher** [comment]
Worked great
