### ISSUE TITLE
Green check marks on failed export

### ISSUE THREAD

**Issue by sstarcher** [utkarshcmu/wizzy#92]
wizzy export dashboards

```
✔ Dashboard ops-health export failed.
Output:
Grafana API response status code = 404
No error body from Grafana API.
```

**Comment by utkarshcmu** [comment]
@sstarcher would you be open to be a maintainer for this project along with me? I can make you a collaborator if you would like to.

**Comment by sstarcher** [comment]
@utkarshcmu I'm up for that.  I don't always have a ton of free time, but I will help when I can.

**Comment by utkarshcmu** [comment]
Fixed in master!
