### ISSUE TITLE
Release 0.5.9

### ISSUE THREAD

**Issue by utkarshcmu** [utkarshcmu/wizzy#98]
@sstarcher I think we should release 0.5.9 as we have a lot of fixes in master after 0.5.8. What do you think? Also, can you test some basic functionalities and we can release it by this weekend.

**Comment by sstarcher** [comment]
I have been using the master branch for about the last week.  What's the process for cutting a release of wizzy.

**Comment by utkarshcmu** [comment]
Currently, I do it from my laptop. But I can move the process to CircleCI.

**Comment by sstarcher** [comment]
@utkarshcmu let me know if I can do anything to help

**Comment by utkarshcmu** [comment]
I released the current master as 0.5.9 👍
